shiny:
  proxy:
    title: MC DataLab
    logo-url: http://www.openanalytics.eu/sites/www.openanalytics.eu/themes/oa/logo.png
    landing-page: /
    heartbeat-rate: 10000
    heartbeat-timeout: 60000
    port: 8080
    authentication: simple
    admin-groups: scientists
    # Simple auth configuration
    users:
    - name: jack
      password: password
      groups: scientists
    - name: jeff
      password: password
      groups: mathematicians
    # Docker configuration
    docker:
      cert-path: /home/none
      url: http://localhost:2375
      host: 127.0.0.1s
      port-range-start: 20000
  apps:
  - name: app1
    display-name: Fraud Detection Example
    description: Application which demonstrates fraud detection on fake data
    docker-cmd: ["R", "-e shinyproxy::run_app1()"]
    docker-image: eizoflexscan/docker-shiny-app1-master
    groups: scientists, mathematicians
  - name: app2
    docker-cmd: ["R", "-e shinyproxy::run_&app2()"]
    docker-image: eizoflexscan/docker-shiny-app2-master
    groups: scientistsss

logging:
  file:
    shinyproxy.log
