shiny:
  proxy:
    title: MC DataLab
    logo-url: http://qualitynights.be/wp-content/uploads/2015/09/MC.jpg
    landing-page: /
    heartbeat-rate: 10000
    heartbeat-timeout: 60000
    port: 8080
    authentication: simple
    admin-groups: scientists
    # Simple auth configuration
    users:
    - name: jack
      password: password
      groups: scientists
    - name: jeff
      password: password
      groups: mathematicians
    # Docker configuration
    docker:
      cert-path: /home/none
      url: http://localhost:2375
      host: 127.0.0.1s
      port-range-start: 20000
  apps:
  - name: app1
    display-name: Demo Application 1
    description: A fake application on fraud
    docker-cmd: ["R", "-e shinyproxy::run_app1()"]
    docker-image: eizoflexscan/docker-shiny-app1-master
    groups: scientists, mathematicians
  - name: app2
  	display-name: Demo Application 2
    description: A basic demo application developed by open analytics
    docker-cmd: ["R", "-e shinyproxy::run_&app2()"]
    docker-image: eizoflexscan/docker-shiny-app2-master
    groups: scientists

logging:
  file:
    shinyproxy.log
